# Generated by Django 3.2 on 2021-05-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerquiz',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
