# Generated by Django 3.2 on 2021-06-05 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerquiz',
            name='quiz',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='answers_quiz', to='core.quiz'),
        ),
        migrations.AlterField(
            model_name='answerquiz',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
