# Generated by Django 3.2 on 2021-06-06 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210605_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerchoice',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.answer'),
        ),
    ]
