# Generated by Django 3.2 on 2021-05-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_answerquiz_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(default='default_slug', unique=True),
            preserve_default=False,
        ),
    ]
