# Generated by Django 3.2 on 2021-06-08 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_answerchoice_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerquiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers_quiz', to='core.quiz'),
        ),
    ]
